accounts/urls.py
from django.urls import path, include, reverse_lazy
from django.contrib.auth import views as auth_views
from . import views
from django.conf.urls import url


app_name = 'accounts'

urlpatterns = [
    # social authentication --> facebook and google
    path('oauth/', include('social_django.urls',
                           namespace='socialauth'), name='socialauth'),
    # user profile page
    path('', views.myaccount, name='myaccount'),
    path('pastorder/', views.pastorder, name="pastorder"),

    # functionality --> login, logout, signup, account activation, assword reset
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', views.logout_customized, name='logout'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='custom/password_reset_form.html',
                                                                 email_template_name='custom/password_reset_email.html', success_url='/accounts/password_reset/done/'), name='password_reset'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(success_url=reverse_lazy('accounts:password_reset_complete')), name='password_reset_confirm'),
    url(r'^', include('django.contrib.auth.urls')),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:productcode>/', views.cart_add, name='cart_add'),
    path('remove/<int:productcode>/', views.cart_remove, name='cart_remove'),
]

my_project/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.conf.urls import url


urlpatterns = [
    path('', include('product.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('seller/', include('seller.urls')),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    url(r'^payment/', include('payment.urls', namespace='payment')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/views.py
from django.contrib.auth import login, logout
from django.contrib.auth.models import User
from django.core.mail import EmailMessage
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from django.contrib.auth.decorators import login_required

from orders.models import OrderItem
from product.models import Review

from .tokens import account_activation_token
from .UserCreationFormCustomized import UserCreationFormCustomized

allowed_host_addr = ['127.0.0.1:8000', 'ecomappmr1.herokuapp.com']


def signup(request):
    if request.method == 'POST':
        form = UserCreationFormCustomized(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            current_host = request.META['HTTP_HOST']
            if current_host in allowed_host_addr:
                mail_subject = 'Activate your account.'
                message = render_to_string('registration_activate_email.html', {
                    'user': user,
                    'domain': current_host,
                    'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                    'token': account_activation_token.make_token(user),
                })
                to_email = form.cleaned_data.get('email')
                email = EmailMessage(
                    mail_subject, message, to=[to_email]
                )
                email.send()
                user.save()
                return render(request, 'registration_activation_message.html')
    else:
        form = UserCreationFormCustomized()
    return render(request, 'signup.html', {'form': form})


def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        user.backend = 'django.contrib.auth.backends.ModelBackend'
        login(request, user)
        return HttpResponse('Your account has been activate successfully')
    else:
        return HttpResponse('Activation link is invalid!')


@login_required
def myaccount(request):
    user = User.objects.filter(id=request.user.id).values()
    return render(request, 'myaccount.html', {'userx': user})


@login_required
def pastorder(request):
    ordered = OrderItem.objects.filter(
        order__user_id=request.user.id).values('order_id', 'product__code', 'product__name', 'quantity', 'price')
    pastreview = Review.objects.filter(user_id=request.user.id).values(
        'user', 'product', 'star', 'comment', 'created_at', 'updated_at', 'user__username', 'product__code')
    return render(request, 'pastorder.html', {'ordered': ordered, 'pastreview': pastreview})


@login_required
def logout_customized(request):
    x = request.session
    if 'cart' in x:
        cartdata = x['cart']
    else:
        cartdata = {}
    logout(request)
    request.session['cart'] = cartdata
    return redirect('product:product_list')

accounts/templates/custom/password_reset_confirm.html
{% extends 'base.html' %}

{% block content %}
{% if validlink %}
<h3>Change password</h3>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Change password</button>
</form>
{% else %}
<p>
    The password reset link was invalid, possibly because it has already been used.
    Please request a new password reset.
</p>
{% endif %}
{% endblock %}

accounts/templates/custom/password_reset_email.html
{% autoescape off %}
To initiate the password reset process for your {{ user.get_username }} ECOM Account,
click the link below:

{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}

If clicking the link above doesn't work, please copy and paste the URL in a new browser
window instead.

Sincerely,
The ECOM Team
{% endautoescape %}

accounts/templates/custom/password_reset_form.html
{% extends 'base.html' %}
{% block title %}Forgot Your Password?{% endblock %}
{% load crispy_forms_tags %}

{% block content %}




<div class="container w-25 mt-3 mx-auto">
    <p>Enter your email address below, and we'll email instructions for setting a new one.</p>
    <div class="w-100   mx-auto ">
        <div class="form">
            <form method="post">
                <fieldset>
                    {% csrf_token %}
                    {{ form|crispy }}
                </fieldset>
                <input type="submit" value="Send me password !" class="btn btn-success btn-md btn-block mt-3">
            </form>
        </div>


    </div>
</div>

{% endblock %}