accounts/urls.py
from django.urls import path, include, reverse_lazy
from django.contrib.auth import views as auth_views
from . import views
from django.conf.urls import url


app_name = 'accounts'

urlpatterns = [
    # social authentication --> facebook and google
    path('oauth/', include('social_django.urls',
                           namespace='socialauth'), name='socialauth'),
    # user profile page
    path('', views.myaccount, name='myaccount'),
    path('pastorder/', views.pastorder, name="pastorder"),

    # functionality --> login, logout, signup, account activation, assword reset
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', views.logout_customized, name='logout'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='custom/password_reset_form.html',
                                                                 email_template_name='custom/password_reset_email.html', success_url='/accounts/password_reset/done/'), name='password_reset'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(success_url=reverse_lazy('accounts:password_reset_complete')), name='password_reset_confirm'),
    url(r'^', include('django.contrib.auth.urls')),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:productcode>/', views.cart_add, name='cart_add'),
    path('remove/<int:productcode>/', views.cart_remove, name='cart_remove'),
]

my_project/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.conf.urls import url


urlpatterns = [
    path('', include('product.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('seller/', include('seller.urls')),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    url(r'^payment/', include('payment.urls', namespace='payment')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

seller/urls.py
from django.urls import path
from . import views

app_name = 'seller'

urlpatterns = [
    path('', views.seller_home, name='seller-home'),
]

seller/models.py
from django.db import models


class SellerProfile(models.Model):
    brand_name = models.CharField(max_length=50, unique=True)
    email = models.EmailField(max_length=254, unique=True)
    pickup_location = models.CharField(max_length=255)

seller/views.py
from django.shortcuts import render
from .sellerRegForm import SellerProfileForm


def seller_home(request):
    if request.method == 'POST':
        form = SellerProfileForm(request.POST)
        if form.is_valid():
            order = form.save() 
    else:
        form = SellerProfileForm()
    return render(request, 'seller-home.html', {'form': form})

seller/templates/seller-base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css"
        integrity="sha256-UzFD2WYH2U1dQpKDjjZK72VtPeWP50NoJjd26rnAdUI=" crossorigin="anonymous" />
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
</head>

<body>

    {% include 'seller-navbar.html' %}

    {% block content %} {% endblock content %}

</body>

</html>

seller/templates/seller-home.html
{% extends 'seller-base.html' %}
{% load static %}
{% block content %}

<form method="POST">
    {% csrf_token %}
    <table>
        {{form.as_table}}
    </table>
    <input type="submit" value="Submit">
</form>
{% endblock content %}

seller/templates/seller-navbar.html
{% load static %}
<style>
    li>a {
        color: black !important;
    }
</style>

<nav class="navbar navbar-expand-md bg-dark navbar-dark font-weight-bold text-white">
    <div class="container-fluid">

        <a class="navbar-brand font-weight-bold" href="/">
            <h3>BRAND</h3>
        </a>

        <form action="/" class="form-inline my-2 my-lg-0 ">
            <input id="searchfield" class="form-control mr-sm-2 ml-4" type="search" value="{{searchterm}}"
                placeholder="Search Item" aria-label="Search" name="search" style="width:430px !important;">
            <button class="searchbutton btn btn-light" type="submit">Search</button>
        </form>

        {% comment %}

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="navbar-nav navbar-right" id="collapsibleNavbar">
            <ul class="navbar-nav navbar-right">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'cart:cart_detail' %}">Cart</a>
                </li>
                <li class="nav-item" id="cartlength">
                    <a class="nav-link" href="{% url 'cart:cart_detail' %}">({{cartlength}})</a>
                </li>
                <li class="nav-item"><a class="nav-link" href="{% url 'seller:seller-home' %}">Seller</a></li>

                {% if user.is_authenticated %}
                <li class="nav-item"><a class="nav-link" href="{% url 'accounts:myaccount' %}">{{ user.username }}</a>
                </li>
                <li class="nav-item"><a class="nav-link" href="{% url 'accounts:logout' %}">logout</a></li>
                {% else %}
                <li class="nav-item"><a class="nav-link" href="{% url 'accounts:login' %}">Login</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'accounts:signup' %}">Sign up</a></li>
                {% endif %}
            </ul>
        </div>
        {% endcomment %}

    </div>
</nav>

<script>
    $(document).ready(function () {
        $('.searchbutton').attr('disabled', true);
        $('#searchfield').keyup(function () {
            if ($(this).val().length != 0)
                $('.searchbutton').attr('disabled', false);
            else
                $('.searchbutton').attr('disabled', true);
        })
    });
</script>