accounts/urls.py
from django.urls import path, include, reverse_lazy
from django.contrib.auth import views as auth_views
from . import views
from django.conf.urls import url


app_name = 'accounts'

urlpatterns = [
    # social authentication --> facebook and google
    path('oauth/', include('social_django.urls',
                           namespace='socialauth'), name='socialauth'),
    # user profile page
    path('', views.myaccount, name='myaccount'),
    path('pastorder/', views.pastorder, name="pastorder"),

    # functionality --> login, logout, signup, account activation, assword reset
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', views.logout_customized, name='logout'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='custom/password_reset_form.html',
                                                                 email_template_name='custom/password_reset_email.html', success_url='/accounts/password_reset/done/'), name='password_reset'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(success_url=reverse_lazy('accounts:password_reset_complete')), name='password_reset_confirm'),
    url(r'^', include('django.contrib.auth.urls')),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:productcode>/', views.cart_add, name='cart_add'),
    path('remove/<int:productcode>/', views.cart_remove, name='cart_remove'),
]

my_project/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.conf.urls import url


urlpatterns = [
    path('', include('product.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('seller/', include('seller.urls')),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    url(r'^payment/', include('payment.urls', namespace='payment')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path
from . import views

app_name = 'product'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('productdetail/<int:code>/', views.product_detail, name='product_detail'),
    path('productreview/<int:code>/', views.product_review, name='product_review'),
    path('review/', views.product_review_RD,
         name='product_review_RD')
]

accounts/views.py
from django.contrib.auth import login, logout
from django.contrib.auth.models import User
from django.core.mail import EmailMessage
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from django.contrib.auth.decorators import login_required

from orders.models import OrderItem
from product.models import Review

from .tokens import account_activation_token
from .UserCreationFormCustomized import UserCreationFormCustomized

allowed_host_addr = ['127.0.0.1:8000', 'ecomappmr1.herokuapp.com']


def signup(request):
    if request.method == 'POST':
        form = UserCreationFormCustomized(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            current_host = request.META['HTTP_HOST']
            if current_host in allowed_host_addr:
                mail_subject = 'Activate your account.'
                message = render_to_string('registration_activate_email.html', {
                    'user': user,
                    'domain': current_host,
                    'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                    'token': account_activation_token.make_token(user),
                })
                to_email = form.cleaned_data.get('email')
                email = EmailMessage(
                    mail_subject, message, to=[to_email]
                )
                email.send()
                user.save()
                return render(request, 'registration_activation_message.html')
    else:
        form = UserCreationFormCustomized()
    return render(request, 'signup.html', {'form': form})


def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        user.backend = 'django.contrib.auth.backends.ModelBackend'
        login(request, user)
        return HttpResponse('Your account has been activate successfully')
    else:
        return HttpResponse('Activation link is invalid!')


@login_required
def myaccount(request):
    user = User.objects.filter(id=request.user.id).values()
    return render(request, 'myaccount.html', {'userx': user})


@login_required
def pastorder(request):
    ordered = OrderItem.objects.filter(
        order__user_id=request.user.id).values('order_id', 'product__code', 'product__name', 'quantity', 'price')
    pastreview = Review.objects.filter(user_id=request.user.id).values(
        'user', 'product', 'star', 'comment', 'created_at', 'updated_at', 'user__username', 'product__code')
    return render(request, 'pastorder.html', {'ordered': ordered, 'pastreview': pastreview})


@login_required
def logout_customized(request):
    x = request.session
    if 'cart' in x:
        cartdata = x['cart']
    else:
        cartdata = {}
    logout(request)
    request.session['cart'] = cartdata
    return redirect('product:product_list')

accounts/templates/myaccount.html
{% extends 'base.html' %}
{% block title %} My Account {% endblock %}
{% block content %}


<div class="container-flex">
    <div class="row">
        <div class="col m-3">
            <div class="card w-3 p-3" style="width: 18rem;">
                <i class='fas fa-user-circle text-center' style='font-size:72px'></i>
                <div class="card-body">
                    <p class="card-text text-center font-weight-bold    ">
                        {{userx.0.first_name}}&nbsp{{userx.0.last_name}}</p>
                </div>
            </div>
            <div class="card w-3 mt-2" style="width: 18rem;">
                <div class="card-body">

                </div>
            </div>
        </div>
        <div class="col">

        </div>
    </div>

</div>



{% endblock %}

{% comment %}

username- {{userx.0.username}}<br>
email- {{userx.0.email}}<br>
first_name- {{userx.0.first_name}}<br>
last_name- {{userx.0.last_name}}<br>

{% endcomment %}

accounts/templates/pastorder.html
{% extends 'myaccount.html' %}
{% block profile %}

<div class="shop">
    {% if ordered|length > 0 %}
    {% for item in ordered %}
    <div class="product border none rounded p-3 mb-2 bg-white text-black shadow p-3 mb-5 bg-red rounded w-20 p-4  d-inline-block "
        style="border: 2px solid black;margin: 5px">

        <div class="d-flex justify-content-center" style="display: inline-block;margin: 5px">Order Id :
            {{ item.order_id}}</div>
        <div class="d-flex justify-content-center" style="display: inline-block;margin: 5px">product Id :
            {{ item.product__name}}</div>
        <div class="d-flex justify-content-center" style="display: inline-block;margin: 5px">quantity :
            {{ item.quantity}}</div>
        <div cass="d-flex justify-content-center" style="display: inline-block;margin: 5px">price : &#8377
            {{ item.price }}</div></br>

        {% for review in pastreview %}

        {% if review.product__code == item.product__code %}

        Given star: {{review.star}}<br>
        Given Review: {{review.comment}}<br>

        <button><a
                href="{% url 'product:product_review_RD' %}?action=delete&product={{review.product__code}}">delete</a>
        </button>

        <form action="{% url 'product:product_review_RD' %}">
            <input type="hidden" name="action" value="edit">
            <input type="hidden" name="product" value="{{review.product__code}}">
            <input type="text" name="reviewedit">
            <input type="submit" value="edit review">
        </form>

        {% endif %} {% endfor %}
        <a href="{% url 'product:product_review' item.product__code %}">Give a review</a>
    </div>
    {% endfor %}


    {% else %}
    No Past Order
    {% endif %}
</div>

{% endblock %}

accounts/templates/registration_activate_email.html
{% autoescape off %}
Hi {{ user.username }},
Please click on the link to confirm your registration,
{{ protocol }}://{{ domain }}{% url 'accounts:activate' uidb64=uid token=token %}
{% endautoescape %}

accounts/templates/registration_activation_message.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <p>
        Please confirm your email address to complete the registration
    </p>
    <p class="text-center">
        <a href="{% url 'product:product_list' %}" class="btn btn-info btn-lg btn-block">Continue Shopping</a>
    </p>
</div>

{% endblock %}

accounts/templates/signup.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Registration{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
<style>
    .form-text {
        display: None;
    }

    .form-group {
        margin-bottom: 0;
    }

    #register-button {
        margin-top: 1rem;
    }
</style>
<div class="w-25 my-0 mx-auto ">
    <div class="form">
        <form method="post">
            <fieldset>
                <legend class="my-0">Create Account</legend>
                {% csrf_token %}
                {{ form|crispy }}
                <input type="submit" value="Create account" class="btn btn-success btn-md btn-block"
                    id="register-button">
            </fieldset>
        </form>
    </div>
    <hr>
    <div>
        <p class="text-center">Or Signup With</p>
        <div class="ml-3 text-center d-flex justify-content-around">
            <a href="{% url 'accounts:socialauth:begin' 'google-oauth2' %}">
                <button class="btn btn-danger" type="button" name="button">Google</button>
            </a>

            <a href="{% url 'accounts:socialauth:begin' 'facebook' %}">
                <button class="btn btn-primary" type="button" name="button">Facebook</button>
            </a>
        </div>
    </div>
    <hr>
    <p class="text-center"><b>Already have an account? <a href="{% url 'accounts:login' %}">Sign in</a></b></p>

</div>
{% endblock %}