cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:productcode>/', views.cart_add, name='cart_add'),
    path('remove/<int:productcode>/', views.cart_remove, name='cart_remove'),
]

my_project/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.conf.urls import url


urlpatterns = [
    path('', include('product.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('seller/', include('seller.urls')),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    url(r'^payment/', include('payment.urls', namespace='payment')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.conf.urls import url
from . import views

app_name = 'orders'

urlpatterns = [
    url(r'^create/$', views.order_create, name='order_create'),
]

product/urls.py
from django.urls import path
from . import views

app_name = 'product'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('productdetail/<int:code>/', views.product_detail, name='product_detail'),
    path('productreview/<int:code>/', views.product_review, name='product_review'),
    path('review/', views.product_review_RD,
         name='product_review_RD')
]

cart/models.py
from django.db import models
from django.contrib.auth.models import User
from product.models import Product


class Cart(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, blank=False, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    objects = models.Manager()

    class Meta:
        db_table = 'cart'

cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 10)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
        choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(
        required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_POST
from django.http import JsonResponse
from product.models import Product
from .cart import Cart


def cartlength(request):
    cartlength = len(Cart(request))
    return {'cartlength': cartlength}


def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart_detail.html', {'cartxx': cart})


@require_POST
def cart_add(request, productcode, quantity=1):
    req = request.POST
    if 'quantity' in req:
        quantity = req['quantity']
    product = get_object_or_404(Product, code=str(productcode))

    cart = Cart(request)
    cart.add(product=product, quantity=quantity)

    priceperone = cart.cart[str(productcode)]['price']
    totalprice = int(quantity) * int(priceperone)
    grandtotal = cart.get_total_price()
    cartlen = len(cart)

    if str(productcode) in request.session['cart'].keys():
        in_cart = True
    else:
        in_cart = False

    responseData = {'cartlen': cartlen, 'totalprice': totalprice,
                    'grandtotal': grandtotal, 'in_cart': in_cart}
    return JsonResponse(responseData)


def cart_remove(request, productcode):
    cart = Cart(request)
    product = get_object_or_404(Product, code=productcode)
    cart.remove(product)
    return redirect('cart:cart_detail')

cart/templates/cart_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Your Cart{% endblock %}
{% block content %}

<div class="container-flex m-4">
    <div class="row">
        <div class="col-8">
            {% if cartxx|length > 0 %}
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Image</th>
                        <th>Product</th>
                        <th>Quantity</th>
                        <th>Unit Price</th>
                        <th>Total</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in cartxx %}
                    {% with product=item.product %}

                    <tr>
                        <td><a class="nav-link" href="{% url 'product:product_detail' product.code %}">
                                <img src="{{ product.image.url }}" style="height: 100px; width: auto;"></a>
                        </td>
                        <td style="height: 150px; width: 200px;">
                            <a class="nav-link"
                                href="{% url 'product:product_detail' product.code %}">{{ product.name }}</a></td>
                        <td>
                            <form action="{% url 'cart:cart_add' productcode=product.code %}" method="POST"
                                class="updatecartquantity" name="{{product.code}}">
                                {% csrf_token %}
                                <select name="quantity">
                                    <option value="" selected disabled hidden>{{item.quantity}}</option>
                                    <option value="1">1</option>
                                    <option value="2">2</option>
                                    <option value="3">3</option>
                                    <option value="4">4</option>
                                    <option value="5">5</option>
                                </select>
                                <input type="submit" value="Update" class="btn btn-info">
                            </form>
                        </td>

                        <td> {{ item.price }} &#8377</td>
                        <td>
                            <span class="totalprice"
                                id="totalprice_{{product.code}}">{{ item.total_price }}</span>&#8377
                        </td>
                        <td>
                            <a href="{% url 'cart:cart_remove' productcode=product.code %}">Remove</a>
                        </td>
                    </tr>
                    {% endwith %}
                    {% endfor %}
                </tbody>
            </table>
        </div>

        <div class="col">
            <p class="text-center">
                <a href="{% url 'product:product_list' %}" class="btn btn-info btn-lg btn-block">Continue Shopping</a>
            </p>
            <p class="text-center">
                Grand Total:
                <h2 class="text-center">
                    <b id="grandtotal"> {{ cartxx.get_total_price }} &#8377</b>
                </h2>
            </p>
            <p class="text-right">
                <a href="{% url 'orders:order_create' %}?next={{request.path}}"
                    class="btn btn-success btn-lg btn-block">Checkout</a>
            </p>
        </div>
    </div>
</div>
{% else %}
<div class="container-flex align-middle">

    <h3 class="text-center align-middle">Your cart is empty</h3>
    <p class="text-center">
        <a href="{% url 'product:product_list' %}" class="btn btn-info btn-lg btn-block">Continue Shopping</a>
    </p>


</div>

{% endif %}



<script>

    $(".updatecartquantity").submit(function (e) {
        e.preventDefault();
        var form = $(this);
        var url = form.attr('action');
        let totalprice = form.attr("name");
        $.ajax({
            type: "POST",
            url: url,
            data: form.serialize(),
            success: function (data) {
                $('#totalprice_' + totalprice + '').html(data.totalprice);
                $("#grandtotal").html(data.grandtotal)
            }
        });
    });
</script>


{% endblock %}

cart/templates/placeorder.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Cart {% endblock %}

{% block content %}

<h1>Your order is Placed !!!</h1>
{{orderplaced}}
{{request.name}}
{% endblock %}